### ISSUE TITLE
Unable to open UML other than popup

### ISSUE THREAD

**Issue by OlliHolli** [vepanimas/intellij-uml-javascript#1]
The Plugin works as expected when opening the diagram **as** a **popup**.
If opened normally it **does not show**.

Using `IntelliJ IDEA Ultimate 2021.3.1 Build #IU-213.6461.79`

_I'm new to git so if anything more is needed please tell me._

EDIT: Added product specifier "IDEA"

**Comment by OlliHolli** [comment]
Hey @vepanimas,
I'm using version `0.1.0` as displayed in the Plugin Manager built in to IntelliJ IDEA Ultimate.
When I click on `Diagrams -> Show Diagram -> Javascript and Typescript Classes`, nothing happens.
When I do the same with `Diagrams -> Show Diagram Popup -> Javascript and Typescript Classes` it works as expected.

I attached a video to illustrate the problem.
![Video](https://user-images.githubusercontent.com/58189060/150494431-350ae810-2cf5-4d26-83ce-56295c4fa62a.mp4)
  
  
*I tried to embed the video into the comment but I believe it didn't work correctly - any help is appreciated.*

**Comment by vepanimas** [comment]
@OlliHolli I can't reproduce it, unfortunately, it works for me 😞. 

Could you please try to create a diagram again, and then invoke `Help > Collect logs and diagnostic data` in the IDE, upload the created archive to https://uploads.jetbrains.com/ and then attach the assigned ID to this ticket? So if the logs contain any sensitive data they will be available only for JB support. Or you could attach them to this ticket instead.

**Comment by OlliHolli** [comment]
@vepanimas I hope you were able to see the video I attached.
I went ahead and uploaded a dump as you suggested.
The ID is as follows: `2022_01_21_KwNmUqodB23QEzJZ`

**Comment by vepanimas** [comment]
@OlliHolli thank you for the logs, but I didn't find anything related there. So, still have no idea, how to reproduce 🤷‍♂️.

Is your project private under NDA or you can share it somehow?

**Comment by OlliHolli** [comment]
@vepanimas It is corporate so I would desist from sharing it publicly. 
As soon as I got time I will try to reproduce the error on my private installation. 
If I can reproduce it I will share it and post another comment on this thread to inform you.

**Comment by vepanimas** [comment]
@OlliHolli ok, no worries, It was expected, but still I decided to try :) I'll take a closer look at the code, maybe I'll catch it somehow.

**Comment by OlliHolli** [comment]
@vepanimas I uploaded a very simple project and invited you to it. You should have the invitation already.
I hope the repos includes what you need.

Also, I don't believe it has something to do with the repos particularly as I was able to replicate the issue on two independent machines and projects. **Note** that I was using the same version of IntelliJ IDEA Ultimate on both systems and also used the same account with settings sync enabled.

As it does not show any problem for you, might it be an issue within my settings?

**Comment by jeremylcarter** [comment]
I am also having the same issue using WebStorm `Show Diagram Popup` is the only way to visualise the diagram.

**Comment by AntoineMaille** [comment]
Same problem here

**Comment by NilsMoller** [comment]
+1

**Comment by ggrundy** [comment]
+1 same problem here Intellij IDEA 2021.2.3 AND Intellij IDEA 2022.1.3 (the latest)

**Comment by vepanimas** [comment]
Unfortunately, I have no idea what's going on here. I've rechecked it with different versions of both WebStorm and IntelliJ IDEA, everything works as expected on my laptop ¯\_(ツ)_/¯.

Do you have any exceptions when trying to open a diagram (the blinking red circle in the bottom right corner)? And what OS do you use? I think that it might be somehow related to the environment because I don't know what to blame otherwise.

**Comment by Lianecx** [comment]
Same problem here.
I am using Windows 10 and Webstorm 2022.2. No exceptions or notifications anywhere 🤔

**Comment by brycetham** [comment]
It's a shame this issue is also occurring on my Windows machine, but for what it's worth, it is working fine on my MacBook.

**Comment by pcafstockf** [comment]
@vepanimas For what its worth, the plugin works for me exactly as described/expected **on my Mac**.   
However under **Windows**, I see the same behavior described above (the diagram displays as a popup, but will not open an editor tab as shown in your original video above).

My logs on Windows might provide a clue:
Diagrams (222.4459.24)

java.util.concurrent.CompletionException: java.lang.NullPointerException: GraphBuilder has been already disposed
              at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
              at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
              at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
              at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
              at com.intellij.util.Futures$inEdt$1.execute(Futures.kt:46)
              at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
              at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1147)
              at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
              at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1810)
              at com.intellij.util.Futures$inEdt$1$$special$$inlined$runInEdt$1.run(actions.kt:60)
              at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
              at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
              at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
              at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
              at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
              at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
              at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
              at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
              at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
              at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
              at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
              at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
              at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
              at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
              at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
              at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
              at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
              at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
              at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
              at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
              at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
              at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
              at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
              at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
              at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NullPointerException: GraphBuilder has been already disposed
              at java.base/java.util.Objects.requireNonNull(Objects.java:233)
              at com.intellij.openapi.graph.impl.builder.GraphBuilderImpl.getProject(GraphBuilderImpl.java:772)
              at com.intellij.openapi.graph.impl.GraphLayoutServiceImpl.V(GraphLayoutServiceImpl.java:1371)
              at com.intellij.openapi.graph.impl.GraphLayoutServiceImpl.V(GraphLayoutServiceImpl.java:1139)
              at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
